### ISSUE TITLE
Add AsRef<str> as an option for add_array_raw

### ISSUE THREAD

**Issue by Hpmason** [vitiral/build_const#3]
I noticed that `ConstValueWriter::add_array_raw` only accepts `&[&str]`.  I think it'd be more useful to allow anything that implements the `AsRef<str>` trait, allowing for structs like `Vec<String>`, as `&[&str]` is very limiting and can require unnecessary conversions. Due to the write! macros, we also need to require `std::fmt::Display` be implemented (the datatypes mentioned already do).

I don't see this breaking any current implementations as `&[&str]` was already limiting.

**Comment by vitiral** [comment]
fixed!
